db.specialites.insert({typeSpecialite: "Allergologue"});
db.specialites.insert({typeSpecialite: "Anesthésiste Réanimateur"});
db.specialites.insert({typeSpecialite: "Angiologue"});
db.specialites.insert({typeSpecialite: "Biologiste"});
db.specialites.insert({typeSpecialite: "Chirurgien Dentiste"});
db.specialites.insert({typeSpecialite: "Chirurgien Oral - Stomatologue"});
db.specialites.insert({typeSpecialite: "Dermatologue"});
db.specialites.insert({typeSpecialite: "Diététicienne Nutritionniste"});
db.specialites.insert({typeSpecialite: "Ergothérapeute"});
db.specialites.insert({typeSpecialite: "Gastro-entérologue"});
db.specialites.insert({typeSpecialite: "Gynécologue"});
db.specialites.insert({typeSpecialite: "Infirmier"});
db.specialites.insert({typeSpecialite: "Kinésithérapeute"});
db.specialites.insert({typeSpecialite: "Médecin du travail"});
db.specialites.insert({typeSpecialite: "Médecin Généraliste"});
db.specialites.insert({typeSpecialite: "Médecin Nucléaire"});
db.specialites.insert({typeSpecialite: "Neurologue"});
db.specialites.insert({typeSpecialite: "Ophtalmologue"});
db.specialites.insert({typeSpecialite: "ORL Oro-Rhino-Laryngologiste"});
db.specialites.insert({typeSpecialite: "Orthodontiste"});
db.specialites.insert({typeSpecialite: "Orthopédiste"});
db.specialites.insert({typeSpecialite: "Orthophoniste"});
db.specialites.insert({typeSpecialite: "Ostéopathe"});
db.specialites.insert({typeSpecialite: "Pédiatre"});
db.specialites.insert({typeSpecialite: "Pédicure-Podologue"});
db.specialites.insert({typeSpecialite: "Pharmacien"});
db.specialites.insert({typeSpecialite: "Physiotérapeute"});
db.specialites.insert({typeSpecialite: "Pneumologue"});
db.specialites.insert({typeSpecialite: "Psychiatre"});
db.specialites.insert({typeSpecialite: "Radiologue"});
db.specialites.insert({typeSpecialite: "Rhumatologue"});
db.specialites.insert({typeSpecialite: "Sage Femme"});
db.specialites.insert({typeSpecialite: "Urgentiste"});
db.specialites.insert({typeSpecialite: "Urologue"});
db.specialites.insert({typeSpecialite: "Autre"});
